title: "first-dry-run"

folder_intermediate_root: "/home/mark/Development/mapping-dependencies/intermediate"

power-designer:
  folder: "PowerDesigner"
  files:
    - "babla1.ldm"
    - "blabla2.ldm"

extractor:
  folder: "RETW"

generator:
  folder: "Generator"
  templates_platform: "dedicated-pool"
  created_ddls_json: "list_created_ddls.json"

publisher:
  vs_project_folder: "MDDE_Release"
  vs_project_file: "./CentralLayer/3. Central Layer.sqlproj"
  codeList_json: "./etl_templates/output/codeList.json"
  codeList_folder: "./etl_templates/input/codeList/"
  mdde_scripts_folder: "./etl_templates/src/generator/mdde_scripts/"

devops:
  organisation: "migratie-dataketen"
  project: "Datawerkorganisatie"
  repo: "DataCenter"
  branch: "collaboration"
  work_item: "23936"
  work_item_description: "Testen automatische uitrol DDL en ETL"